default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bagstr_dev

test:
  <<: *default
  database: bagstr_test

production:
  <<: *default
  database: bagstr_pro
  username: bagstr
  password: <%= ENV['BAGSTR_DATABASE_PASSWORD'] %>
